version: "3.9"

services:
  isaac-sim-service:
    image: isaac-sim
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    environment:
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /home/jason/Service/omniverse/cache/kit:/isaac-sim/kit/cache:rw
      - /home/jason/Service/omniverse/cache/ov:/root/.cache/ov:rw
      - /home/jason/Service/omniverse/cache/pip:/root/.cache/pip:rw
      - /home/jason/Service/omniverse/cache/glcache:/root/.cache/nvidia/GLCache:rw
      - /home/jason/Service/omniverse/cache/computecache:/root/.nv/ComputeCache:rw
      - /home/jason/Service/omniverse/logs:/root/.nvidia-omniverse/logs:rw
      - /home/jason/Service/omniverse/data:/root/.local/share/ov/data:rw
      - /home/jason/Service/omniverse/documents:/root/Documents:rw
    runtime: nvidia
    entrypoint: ["bash", "-c", "source /opt/ros/humble/setup.bash && ./runheadless.native.sh -v"]