version: '3.8'
services:
  ollama:
    image: kuzco
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 14444:14444
    volumes:
      - ./data:/root/.kuzco
    container_name: ollama
    tty: true
    restart: unless-stopped
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu